changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - github-actions[bot]
  categories:
    - title: "Features"
      labels:
        - enhancement
        - feature
    - title: "Bug Fixes"
      labels:
        - bug
        - fix
    - title: "Maintenance"
      labels:
        - ops
      title_prefixes:
        - "ops:"
        - "docs:"
        - "doc:"
        - "readme:"
        - "tests:"
        - "test:"
        - "misc:"
        - "update"
        - "github"
        - "release"
        - "chore:"
        - "signed the CLA"